### ISSUE TITLE
TaylorSeriesLinearAttn object has no attribute taylor_expand_fn

### ISSUE THREAD

**Issue by JingboYang** [lucidrains/taylor-series-linear-attention#5]
I have noticed that with the latest version 0.1.12, the following error will occur.
```
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'TaylorSeriesLinearAttn' object has no attribute 'taylor_expand_fn
```

I believe this is related to the latest change https://github.com/lucidrains/taylor-series-linear-attention/commit/4d99e804d4492b2dec3f2348459493039e5acf26#diff-b6289766afc49158be388c80fa032670c16c7789f55ae0baee8bb649d3b53bc9R121

This error prevents the example code in meshgpt-pytorch from running.
Downgrading to 0.1.11`pip install --upgrade --force-reinstall taylor-series-linear-attention==0.1.11` solves the problem.

Thanks in advance if you could take a look.

**Comment by lucidrains** [comment]
@JingboYang hmm, it runs for me

are you using a pretrained model?

**Comment by JingboYang** [comment]
Ya I am using `transformer = MeshTransformer.from_pretrained("MarcusLoren/MeshGPT-preview").to(device)` as shown in the tutorial code.

**Comment by lucidrains** [comment]
@JingboYang ah yea

ok, i've pinned the version used at meshgpt to 0.1.11

thanks for reporting!
